name: Create Archive
on: [release, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'QuickEPGP-classic.zip'
        exclusions: '.git .idea .vscode .gitignore'
